title: Novick Lab Docs
description: A site containing Novick Lab docs
theme: just-the-docs

url: https://neurodoclove.github.io/novick-lab

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
